# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "aae1f2e937ada1d2507afd4634c322ba"
application_url = "https://medicaid-temporal-formal-ideas.trycloudflare.com"
embedded = true
name = "hello-world"
handle = "hello-world-484"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://medicaid-temporal-formal-ideas.trycloudflare.com/auth/callback",
  "https://medicaid-temporal-formal-ideas.trycloudflare.com/auth/shopify/callback",
  "https://medicaid-temporal-formal-ideas.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
